Only clone current project

diff --git a/ce-dev/ansible/set-current.sh.j2 b/ce-dev/ansible/set-current.sh.j2
--- a/ce-dev/ansible/set-current.sh.j2
+++ b/ce-dev/ansible/set-current.sh.j2
@@ -11,18 +11,28 @@ cd "$OWN_DIR" || exit 1
 OWN_DIR=$(pwd -P)
 CURRENT_PROJECT=""
 
-{% for name, wiki in wikis.iteritems() %}
-if [ ! -d "$OWN_DIR/content/{{ name }}" ]; then
-  git clone {{ wiki.src }} --branch {{ wiki.src_branch }} "$OWN_DIR/content/{{ name }}"
-fi
-if [ ! -d "$OWN_DIR/public/{{ name }}" ]; then
-{% if wiki.dest is defined and wiki.dest %}
-  git clone {{ wiki.dest }} --branch {{ wiki.dest_branch }} "$OWN_DIR/public/{{ name }}"
-{% else %}
-  mkdir "$OWN_DIR/public/{{ name }}"
-{% endif %}
-fi
-{% endfor %}
+clone_current(){
+  case $CURRENT_PROJECT in
+    {% for name, wiki in wikis.iteritems() %}
+    "{{ name }}")
+      if [ ! -d "$OWN_DIR/content/{{ name }}" ]; then
+        git clone {{ wiki.src }} --branch {{ wiki.src_branch }} "$OWN_DIR/content/{{ name }}"
+      fi
+      if [ ! -d "$OWN_DIR/public/{{ name }}" ]; then
+      {% if wiki.dest is defined and wiki.dest %}
+        git clone {{ wiki.dest }} --branch {{ wiki.dest_branch }} "$OWN_DIR/public/{{ name }}"
+      {% else %}
+        mkdir "$OWN_DIR/public/{{ name }}"
+      {% endif %}
+      fi
+    ;;
+    {% endfor %}
+    *)
+      echo "Invalid choice"
+      exit 1
+    ;;
+  esac
+}
 
 prompt_from_list(){
   echo "Which project do you want to use?"
@@ -51,7 +61,11 @@ else
   prompt_from_list
 fi
 
+clone_current
+
 echo "current: $CURRENT_PROJECT" > "$OWN_DIR/ce-dev/ansible/current.yml"
+
 cd "$OWN_DIR"
+
 ce-dev start
 ce-dev deploy
